/**
 * Auto-registration for tools.
 *
 * This module registers all tools with the global registry when imported.
 * Adding a new tool to the tools barrel file will automatically register it.
 */

import { globalRegistry } from "../core/registry";

// ============================================================
// JSON tools
// ============================================================
import {
  jsonFormatter,
  jsonValidator,
  jsonMinify,
  jsonPathQuery,
  jsonJmespath,
  jsonDiff,
  jsonSortKeys,
  jsonFlatten,
  jsonUnflatten,
  jsonEscape,
  jsonUnescape,
  jsonToYaml,
  jsonToXml,
  jsonToCsv,
  jsonRemoveNulls,
  jsonMerge,
  jsonSizeAnalyzer,
  jsonTreeViewer,
  jsonSchemaGenerator,
  jsonSchemaToTypescript,
  jsonSchemaValidatorApi,
  jsonSchemaValidatorTool,
  jsonSchemaFaker,
  jsonToTypescript,
  jsonToGo,
  jsonToJava,
  jsonToPython,
  jsonToRust,
  jsonToCsharp,
} from "./json";

// ============================================================
// YAML tools
// ============================================================
import {
  yamlFormatter,
  yamlToJson,
  yamlToXml,
  yamlMinify,
  yamlDiff,
  yamlMerge,
  yamlPathQuery,
  yamlSortKeys,
  yamlLint,
  yamlSplitter,
} from "./yaml";

// ============================================================
// XML tools
// ============================================================
import {
  xmlFormatter,
  xmlValidator,
  xmlToJson,
  xmlToYaml,
  xmlMinify,
  xmlXpath,
  xmlDiff,
  xmlEscape,
  xmlToCsv,
} from "./xml";

// ============================================================
// CSV tools
// ============================================================
import {
  csvFormatter,
  csvValidator,
  csvToJson,
  csvToYaml,
  csvToXml,
  csvDiff,
  csvMerge,
  csvFilter,
  csvSort,
  csvStats,
  csvViewer,
  csvToSql,
  csvColumnExtractor,
  csvDeduplicator,
  csvToTsv,
  csvToMarkdown,
} from "./csv";

// ============================================================
// TOML tools
// ============================================================
import { tomlFormatter, tomlValidator, tomlToJson, tomlToYaml } from "./toml";

// ============================================================
// Data tools (INI, conversions, binary viewers)
// ============================================================
import {
  iniFormatter,
  iniValidator,
  iniToJson,
  jsonToToml,
  jsonToIni,
  jsoncStripper,
  messagepackViewer,
  protobufViewer,
  avroViewer,
  ndjsonParser,
  jsonToNdjson,
  hjsonToJson,
  json5ToJson,
  avroSchemaFormatter,
  protobufEditor,
} from "./data";

// ============================================================
// Encoding tools
// ============================================================
import {
  base64Encode,
  base64Decode,
  base64urlEncode,
  base64urlDecode,
  base32EncodeDecode,
  base58EncodeDecode,
  base62EncodeDecode,
  hexEncode,
  hexDecode,
  binaryToText,
  textToBinary,
  octalConverter,
  urlEncode,
  urlDecode,
  urlEncodeFull,
  urlParser as encodingUrlParser,
  urlBuilder as encodingUrlBuilder,
  queryStringParser,
  queryStringBuilder,
  dataUrlBuilder,
  unicodeEscape,
  unicodeUnescape,
  htmlEntityEncode,
  htmlEntityDecode,
  jsEscape,
  jsUnescape,
  encodingJsonEscape,
  encodingJsonUnescape,
  punycodeEncode,
  punycodeDecode,
  utf8ToUtf16,
  utf16ToUtf8,
  latin1Converter,
  asciiTable,
  unicodeLookup,
  characterInspector,
  charsetDetector,
  bomRemover,
  anyBaseConverter,
  morseCode,
  natoAlphabet,
} from "./encoding";

// ============================================================
// Text tools
// ============================================================
import {
  caseConverter,
  slugify,
  textReverser,
  lineSorter,
  lineDeduplicator,
  lineShuffler,
  lineNumberer,
  emptyLineRemover,
  whitespaceCleaner,
  textTrimmer,
  findReplace,
  textWrapper,
  prefixSuffixAdder,
  columnAligner,
  textTruncator,
  palindromeChecker,
  rot13Encoder,
  readingTime,
  wordFrequency,
  textStatistics,
  readabilityScore,
  letterFrequency,
  ngramGenerator,
  textDiff,
  similarityScore,
  plagiarismHighlighter,
  loremIpsum,
  emailExtractor,
  urlExtractor,
  phoneExtractor,
  ipExtractor,
  hashtagExtractor,
  mentionExtractor,
  numberExtractor,
  dateExtractor,
  keywordExtractor,
  languageDetector,
  anagramGenerator,
  semanticDiff,
  fakeName,
  fakeAddress,
  fakeCompany,
  soundexGenerator,
  metaphoneGenerator,
} from "./text";

// ============================================================
// Markdown tools
// ============================================================
import {
  markdownToHtml,
  htmlToMarkdown,
  markdownFormatter,
  markdownTocGenerator,
  markdownLinkExtractor,
  markdownImageExtractor,
  markdownTableGenerator,
  markdownTableFormatter,
  markdownToPlainText,
  markdownEscaper,
  frontmatterEditor,
  markdownToSlack,
  slackToMarkdown,
  markdownToJira,
  jiraToMarkdown,
  markdownToDiscord,
  markdownToBbcode,
  readmeGenerator,
  licensePicker,
  changelogGenerator,
  contributingGuide,
  markdownLinter,
  badgeGenerator,
  issueTemplate,
  prTemplate,
  codeOfConduct,
  markdownLinkChecker,
  markdownToConfluence,
  rstToMd,
  asciidocToMd,
  textileToMd,
} from "./markdown";

// ============================================================
// API tools
// ============================================================
import {
  curlConverter,
  openapiViewer,
  openapiValidator,
  openapiFormatter,
  openapiToJson,
  jsonToOpenapi,
  openapiDiff,
  openapiMock,
  swagger2ToOpenapi3,
  openapiMerger,
  openapiSplitter,
  jsonSchemaToOpenapi,
  openapiToJsonSchema,
  graphqlSchemaViewer,
  requestBuilder,
  responseFormatter,
  graphqlFormatterApi,
  graphqlToTypescript,
  restToGraphql,
  webhookCurlGenerator,
  apiMockGenerator,
  postmanToCurl,
  openapiToTypescript,
  graphqlSchemaGenerator,
  gitignoreGenerator,
  awsArnParser,
  cloudResourceNamer,
} from "./api";

// ============================================================
// Code tools
// ============================================================
import {
  jsFormatter,
  graphqlFormatter,
  mdFormatter,
  pythonFormatter,
  jsMinify,
  jsonMinifyCode,
  xmlMinifyCode,
  graphqlMinify,
  tsMinify,
  batchMinify,
  jsObfuscator,
  codeComplexity,
  syntaxHighlighter,
  lineCounter,
  codeToImage,
  commentStripper,
  deadCodeFinder,
  eslintConfigGenerator,
  prettierConfigGenerator,
  editorconfigGenerator,
  tsconfigGenerator,
  babelConfigGenerator,
  envGenerator,
  envParser,
  envValidator,
  packageJsonValidator,
  packageJsonMerger,
  semverBumper,
  sqlToTypescript,
} from "./code";

// ============================================================
// Color tools
// ============================================================
import {
  hexToRgb,
  rgbToHexTool,
  hexToHsl,
  hslToHexTool,
  rgbToHslTool,
  hslToRgbTool,
  rgbToCmykTool,
  cmykToRgbTool,
  hexToHsv,
  colorNameToHex,
  hexToColorName,
  allColorFormats,
  colorPicker,
  randomColor,
  paletteGenerator,
  complementaryColor,
  analogousColors,
  triadicColors,
  splitComplementary,
  colorShades,
  colorTints,
  gradientGenerator,
  contrastChecker,
  colorBlindnessSimulator,
  colorBrightness,
  colorLuminance,
  colorDistance,
  colorMixer,
  colorInverter,
} from "./color";

// ============================================================
// Communication tools
// ============================================================
import {
  emailHeaderParser,
  emailTemplateBuilder,
  emailToMarkdown,
  emailAddressParser,
  emailSignatureGenerator,
  spfRecordGenerator,
  dkimValidator,
  telegramFormatter,
  teamsFormatter,
  ircFormatter,
} from "./communication";

// ============================================================
// Crypto tools
// ============================================================
import {
  md5Hash,
  sha1Hash,
  sha256Hash,
  sha384Hash,
  sha512Hash,
  sha3Hash,
  blake2Hash,
  ripemd160Hash,
  crc32Checksum,
  adler32Checksum,
  xxhash,
  murmurhash,
  hashIdentifier,
  multiHash,
  hmacSha256,
  hmacSha512,
  pbkdf2,
  bcryptGenerator,
  bcryptVerifier,
  aesEncrypt,
  aesDecrypt,
  rsaEncrypt,
  rsaDecrypt,
  chacha20Encrypt,
  chacha20Decrypt,
  rsaKeyGenerator,
  ecKeyGenerator,
  ed25519KeyGenerator,
  pemParser,
  jwkConverter,
  csrDecoder,
  certificateDecoder,
  keyFingerprint,
  passwordGenerator,
  passphraseGenerator,
  passwordStrength,
  pinGenerator,
  memorablePassword,
  passwordHashCheck,
  passwordEntropy,
  apiKeyGenerator,
  stringHash,
} from "./crypto";

// ============================================================
// CSS tools
// ============================================================
import {
  cssFormatter,
  cssMinify,
  cssValidator,
  scssToCss,
  lessToCss,
  cssToScss,
  cssSpecificity,
  cssGradientGenerator,
  cssBoxShadow,
  cssBorderRadius,
  cssFlexboxGenerator,
  cssGridGenerator,
} from "./css";

// ============================================================
// DateTime tools
// ============================================================
import {
  unixTimestamp,
  iso8601Converter,
  rfc2822Converter,
  epochConverter,
  dateFormatter,
  dateParser,
  julianDayConverter,
  excelDateConverter,
  relativeTime,
  dateToWords,
  timezoneConverter,
  utcConverter,
  dateDifference,
  dateAddSubtract,
  ageCalculator,
  workdaysCalculator,
  weekNumber,
  quarterCalculator,
  dayOfYear,
  leapYearChecker,
  daysInMonth,
  dateRangeGenerator,
  timezoneList,
  worldClock,
  durationCalculator,
  durationFormatter,
  timeParser,
  time12h24hConverter,
  countdownCalculator,
  meetingPlanner,
  cronBuilder,
  cronParser,
  cronNextRuns,
  cronValidator,
  cronToEnglish,
  englishToCron,
  rateLimiterCalculator,
  intervalCalculator,
  calendarGenerator,
  holidayLookup,
  icalGenerator,
  icalParser,
  vcardGenerator,
  vcardParser,
} from "./datetime";

// ============================================================
// Diagram tools
// ============================================================
import {
  mermaidRenderer,
  mermaidEditor,
  plantumlAnalyzer,
  graphvizAnalyzer,
  sequenceDiagramEditor,
  flowchartEditor,
  erDiagramEditor,
  ganttChartEditor,
  mindMapEditor,
  asciiDiagram,
  qrCodeGenerator,
  qrWithLogo,
  styledQrCode,
  wifiQrCode,
  vcardQrCode,
  urlQrCode,
  bulkQrGenerator,
  code128Generator,
  code39Generator,
  ean13Generator,
  ean8Generator,
  upcAGenerator,
  upcEGenerator,
  itfGenerator,
  pdf417Info,
  dataMatrixInfo,
  lineChartGenerator,
  barChartGenerator,
  pieChartGenerator,
  scatterPlotGenerator,
  areaChartGenerator,
  radarChartGenerator,
  sparklineGenerator,
  jsonToChart,
} from "./diagram";

// ============================================================
// Feeds tools
// ============================================================
import {
  rssParser,
  atomParser,
  rssGenerator,
  atomGenerator,
  rssValidator,
  feedMerger,
  jsonFeedParser,
  opmlParser,
  schemaOrgGenerator as feedsSchemaOrgGenerator,
  schemaOrgValidator,
  jsonLdEditor,
  microdataExtractor,
  richSnippetPreview,
  breadcrumbGenerator,
  faqSchemaGenerator,
  productSchemaGenerator,
} from "./feeds";

// ============================================================
// HTML tools
// ============================================================
import {
  htmlFormatter,
  htmlMinify,
  htmlValidator,
  htmlToText,
  htmlEntityEncoder,
  htmlEntityDecoder,
  htmlAttributeRemover,
  htmlPlayground,
  htmlTableGenerator,
  htmlListGenerator,
  faviconGenerator,
} from "./html";

// ============================================================
// Image tools
// ============================================================
import {
  pngToJpg,
  jpgToPng,
  imageToWebp,
  webpToPng,
  imageToBase64,
  base64ToImage,
  imageToDataUrl,
  imageResizer,
  imageCropper,
  imageRotator,
  imageFlipper,
  imageCompressor,
  aspectRatioCalculator,
  imageBorderAdder,
  imageWatermark,
  roundCorners,
  circleCrop,
  thumbnailGenerator,
  imageSplitter,
  grayscale,
  sepia,
  invertColors,
  brightnessAdjuster,
  contrastAdjuster,
  blurFilter,
  sharpenFilter,
  pixelate,
  posterize,
  duotone,
  imageInfo,
  exifReader,
  exifRemover,
  colorPickerFromImage,
  dominantColors,
  imageHistogram,
  imageDiff,
  placeholderImage,
} from "./image";

// ============================================================
// JWT tools
// ============================================================
import {
  jwtDecoder,
  jwtEncoder,
  jwtDebugger,
  jwtExpiryChecker,
  jwtClaimsBuilder,
  jwtRs256Generator,
  pasetoDecoder,
  oauthTokenDecoder,
  samlDecoder,
  fernetEncoder,
} from "./jwt";

// ============================================================
// Identifiers tools
// ============================================================
import {
  uuidV1Generator,
  uuidV4Generator,
  uuidV5Generator,
  uuidV7Generator,
  ulidGenerator,
  nanoidGenerator,
  cuidGenerator,
  cuid2Generator,
  snowflakeIdGenerator,
  ksuidGenerator,
  objectidGenerator,
  shortIdGenerator,
  bulkIdGenerator,
  sessionTokenGenerator,
} from "./identifiers";

// ============================================================
// Git tools
// ============================================================
import {
  gitBranchNamer,
  gitCommandBuilder,
  gitCommitMessage,
  gitDiffViewer,
  gitignoreBuilder,
  gitIgnoreChecker,
  conventionalCommits,
  changelogParser,
} from "./git";

// ============================================================
// DevOps tools
// ============================================================
import {
  dockerfileGenerator,
  dockerfileLinter,
  composeGenerator,
  composeValidator,
  k8sYamlGenerator,
  k8sYamlValidator,
  helmValuesGenerator,
  containerImageParser,
} from "./devops";

// ============================================================
// Legal tools
// ============================================================
import {
  privacyPolicyGenerator,
  cookiePolicyGenerator,
  termsOfServiceGenerator,
  copyrightNoticeGenerator,
  disclaimerGenerator,
  gdprStatementGenerator,
} from "./legal";

// ============================================================
// Reference tools
// ============================================================
import {
  countryCodeReference,
  currencyCodeReference,
  languageCodeReference,
  keyboardShortcutsReference,
  emojiReference,
} from "./reference";

// ============================================================
// Math tools
// ============================================================
import {
  lengthConverter,
  weightConverter,
  temperatureConverter,
  volumeConverter,
  areaConverter,
  speedConverter,
  timeUnitConverter,
  dataSizeConverter,
  pressureConverter,
  energyConverter,
  powerConverter,
  frequencyConverter,
  angleConverter,
  forceConverter,
  fuelEconomyConverter,
  currencyConverter,
  numberFormatter,
  percentageCalculator,
  ratioCalculator,
  fractionCalculator,
  percentageChange,
  tipCalculator,
  discountCalculator,
  markupCalculator,
  vatCalculator,
  compoundInterest,
  loanCalculator,
  bmiCalculator,
  expressionEvaluator,
  scientificCalculator,
  matrixCalculator,
  primeChecker,
  primeFactorization,
  gcdLcmCalculator,
  factorialCalculator,
  fibonacciGenerator,
  randomNumberGenerator,
  statisticsCalculator,
  standardDeviation,
  permutationCombination,
  quadraticSolver,
  bitwiseCalculator,
  romanNumeralConverter,
  scientificNotation,
} from "./math";

// ============================================================
// Misc tools
// ============================================================
import {
  stringLength,
  stringObfuscator,
  characterRepeater,
  pigLatin,
  leetSpeak,
  emojiConverter,
  zalgoText,
  upsideDownText,
  fancyText,
  mimeTypeReference,
  htmlEntityReference,
} from "./misc";

// ============================================================
// Network tools
// ============================================================
import {
  httpStatusReference as networkHttpStatusReference,
  subnetCalculator,
  cidrCalculator,
  ipRangeCalculator,
  macAddressLookup,
  curlBuilder as networkCurlBuilder,
  cidrToRange,
  integerToIp,
  ipInCidrChecker,
  ipInfoParser,
  ipToInteger,
  ipv6Compressor,
  ipv6Expander,
  rangeToCidr,
  harAnalyzer,
  httpHeadersReference,
  httpHeaderParser,
  mimeTypeLookup,
} from "./network";

// ============================================================
// Regex tools
// ============================================================
import {
  regexTester,
  regexExplainer,
  regexReplace,
  regexSplit,
  regexExtract,
  regexGroups,
  regexFlagsTester,
  regexEscape,
  globToRegex,
  regexToGlob,
  regexOptimizer,
  commonPatterns,
  emailRegex,
  urlRegex,
  phoneRegex,
  ipRegex,
  dateRegex,
  creditCardRegex,
  passwordRegex,
} from "./regex";

// ============================================================
// SQL tools
// ============================================================
import {
  sqlFormatter,
  sqlMinify,
  sqlValidator,
  sqlToJsonLegacy,
  sqlParser,
  sqlExplainer,
  sqlToNosql,
  sqlDialectConverter,
  sqlQueryBuilder,
  sqlIndexSuggester,
  jsonToSqlInsert,
  csvToSqlInsert,
  connectionStringBuilder,
  dsnParser,
  redisCommandBuilder,
  mongodbQueryBuilder,
  elasticsearchQueryBuilder,
  databaseUrlConverter,
  erDiagramGenerator,
  sqlCreateTableGenerator,
  sqlDiff,
  sqlEscape,
  sqlExplainVisualizer,
  sqlIndexAdvisor,
  sqlInsertGenerator,
  sqlMigrationGenerator,
  sqlSchemaDiff,
  sqlSelectBuilder,
} from "./sql";

// ============================================================
// SVG tools
// ============================================================
import {
  svgOptimizer,
  svgViewer,
  svgToPngConverter,
  svgToJpg,
  svgToBase64,
  svgToDataUri,
  svgFormatter,
  svgPathEditor,
  svgToCss,
  svgSpriteGenerator,
  svgColorChanger,
  svgWaveGenerator,
  svgBlobGenerator,
  svgPatternGenerator,
  svgAvatarGenerator,
  svgDividerGenerator,
  svgBackgroundGenerator,
} from "./svg";

// ============================================================
// Validation tools
// ============================================================
import {
  emailValidator,
  urlValidator,
  phoneValidator,
  uuidValidator as validationUuidValidator,
  macAddressValidator,
  ipv4Validator,
  ipv6Validator,
  domainValidator,
  hostnameValidator,
  slugValidator,
  semverValidator,
  hexColorValidator,
  creditCardValidator,
  isbnValidator,
  issnValidator,
  doiValidator,
  validationJsonValidator,
  validationXmlValidator,
  validationYamlValidator,
  validationTomlValidator,
  validationCsvValidator,
  validationHtmlValidator,
  validationCssValidator,
  javascriptValidator,
  sqlValidator as validationSqlValidator,
  cronValidatorTool,
} from "./validation";

// ============================================================
// Web tools
// ============================================================
import {
  metaTagGenerator,
  ogGenerator,
  twitterCardGenerator,
  schemaOrgGenerator as webSchemaOrgGenerator,
  robotsTxtGenerator,
  robotsTxtValidator,
  sitemapGenerator,
  sitemapValidator,
  canonicalUrlBuilder,
  hreflangGenerator,
  metaPreview,
  socialPreview,
  cspBuilder,
  cspValidator,
  corsBuilder,
  sriHashGenerator,
  securityHeadersCheck,
  hstsBuilder,
  permissionsPolicyBuilder,
  xssFilterTester,
} from "./web";

/**
 * All tools available in the package.
 * Add new tools here to have them auto-registered.
 */
const ALL_TOOLS = [
  // JSON tools
  jsonFormatter,
  jsonValidator,
  jsonMinify,
  jsonPathQuery,
  jsonJmespath,
  jsonDiff,
  jsonSortKeys,
  jsonFlatten,
  jsonUnflatten,
  jsonEscape,
  jsonUnescape,
  jsonToYaml,
  jsonToXml,
  jsonToCsv,
  jsonRemoveNulls,
  jsonMerge,
  jsonSizeAnalyzer,
  jsonTreeViewer,
  jsonSchemaGenerator,
  jsonSchemaToTypescript,
  jsonSchemaValidatorApi,
  jsonSchemaValidatorTool,
  jsonSchemaFaker,
  jsonToTypescript,
  jsonToGo,
  jsonToJava,
  jsonToPython,
  jsonToRust,
  jsonToCsharp,
  // YAML tools
  yamlFormatter,
  yamlToJson,
  yamlToXml,
  yamlMinify,
  yamlDiff,
  yamlMerge,
  yamlPathQuery,
  yamlSortKeys,
  yamlLint,
  yamlSplitter,
  // XML tools
  xmlFormatter,
  xmlValidator,
  xmlToJson,
  xmlToYaml,
  xmlMinify,
  xmlXpath,
  xmlDiff,
  xmlEscape,
  xmlToCsv,
  // CSV tools
  csvFormatter,
  csvValidator,
  csvToJson,
  csvToYaml,
  csvToXml,
  csvDiff,
  csvMerge,
  csvFilter,
  csvSort,
  csvStats,
  csvViewer,
  csvToSql,
  csvColumnExtractor,
  csvDeduplicator,
  csvToTsv,
  csvToMarkdown,
  // TOML tools
  tomlFormatter,
  tomlValidator,
  tomlToJson,
  tomlToYaml,
  // Data tools
  iniFormatter,
  iniValidator,
  iniToJson,
  jsonToToml,
  jsonToIni,
  jsoncStripper,
  messagepackViewer,
  protobufViewer,
  avroViewer,
  ndjsonParser,
  jsonToNdjson,
  hjsonToJson,
  json5ToJson,
  avroSchemaFormatter,
  protobufEditor,
  // Encoding tools
  base64Encode,
  base64Decode,
  base64urlEncode,
  base64urlDecode,
  base32EncodeDecode,
  base58EncodeDecode,
  base62EncodeDecode,
  hexEncode,
  hexDecode,
  binaryToText,
  textToBinary,
  octalConverter,
  urlEncode,
  urlDecode,
  urlEncodeFull,
  encodingUrlParser,
  encodingUrlBuilder,
  queryStringParser,
  queryStringBuilder,
  dataUrlBuilder,
  unicodeEscape,
  unicodeUnescape,
  htmlEntityEncode,
  htmlEntityDecode,
  jsEscape,
  jsUnescape,
  encodingJsonEscape,
  encodingJsonUnescape,
  punycodeEncode,
  punycodeDecode,
  utf8ToUtf16,
  utf16ToUtf8,
  latin1Converter,
  asciiTable,
  unicodeLookup,
  characterInspector,
  charsetDetector,
  bomRemover,
  anyBaseConverter,
  morseCode,
  natoAlphabet,
  // Text tools
  caseConverter,
  slugify,
  textReverser,
  lineSorter,
  lineDeduplicator,
  lineShuffler,
  lineNumberer,
  emptyLineRemover,
  whitespaceCleaner,
  textTrimmer,
  findReplace,
  textWrapper,
  prefixSuffixAdder,
  columnAligner,
  textTruncator,
  palindromeChecker,
  rot13Encoder,
  readingTime,
  wordFrequency,
  textStatistics,
  readabilityScore,
  letterFrequency,
  ngramGenerator,
  textDiff,
  similarityScore,
  plagiarismHighlighter,
  loremIpsum,
  emailExtractor,
  urlExtractor,
  phoneExtractor,
  ipExtractor,
  hashtagExtractor,
  mentionExtractor,
  numberExtractor,
  dateExtractor,
  keywordExtractor,
  languageDetector,
  anagramGenerator,
  semanticDiff,
  fakeName,
  fakeAddress,
  fakeCompany,
  soundexGenerator,
  metaphoneGenerator,
  // Markdown tools
  markdownToHtml,
  htmlToMarkdown,
  markdownFormatter,
  markdownTocGenerator,
  markdownLinkExtractor,
  markdownImageExtractor,
  markdownTableGenerator,
  markdownTableFormatter,
  markdownToPlainText,
  markdownEscaper,
  frontmatterEditor,
  markdownToSlack,
  slackToMarkdown,
  markdownToJira,
  jiraToMarkdown,
  markdownToDiscord,
  markdownToBbcode,
  readmeGenerator,
  licensePicker,
  changelogGenerator,
  contributingGuide,
  markdownLinter,
  badgeGenerator,
  issueTemplate,
  prTemplate,
  codeOfConduct,
  markdownLinkChecker,
  markdownToConfluence,
  rstToMd,
  asciidocToMd,
  textileToMd,
  // API tools
  curlConverter,
  openapiViewer,
  openapiValidator,
  openapiFormatter,
  openapiToJson,
  jsonToOpenapi,
  openapiDiff,
  openapiMock,
  swagger2ToOpenapi3,
  openapiMerger,
  openapiSplitter,
  jsonSchemaToOpenapi,
  openapiToJsonSchema,
  graphqlSchemaViewer,
  requestBuilder,
  responseFormatter,
  graphqlFormatterApi,
  graphqlToTypescript,
  restToGraphql,
  webhookCurlGenerator,
  apiMockGenerator,
  postmanToCurl,
  openapiToTypescript,
  graphqlSchemaGenerator,
  gitignoreGenerator,
  awsArnParser,
  cloudResourceNamer,
  // Code tools
  jsFormatter,
  graphqlFormatter,
  mdFormatter,
  pythonFormatter,
  jsMinify,
  jsonMinifyCode,
  xmlMinifyCode,
  graphqlMinify,
  tsMinify,
  batchMinify,
  jsObfuscator,
  codeComplexity,
  syntaxHighlighter,
  lineCounter,
  codeToImage,
  commentStripper,
  deadCodeFinder,
  eslintConfigGenerator,
  prettierConfigGenerator,
  editorconfigGenerator,
  tsconfigGenerator,
  babelConfigGenerator,
  envGenerator,
  envParser,
  envValidator,
  packageJsonValidator,
  packageJsonMerger,
  semverBumper,
  sqlToTypescript,
  // Color tools
  hexToRgb,
  rgbToHexTool,
  hexToHsl,
  hslToHexTool,
  rgbToHslTool,
  hslToRgbTool,
  rgbToCmykTool,
  cmykToRgbTool,
  hexToHsv,
  colorNameToHex,
  hexToColorName,
  allColorFormats,
  colorPicker,
  randomColor,
  paletteGenerator,
  complementaryColor,
  analogousColors,
  triadicColors,
  splitComplementary,
  colorShades,
  colorTints,
  gradientGenerator,
  contrastChecker,
  colorBlindnessSimulator,
  colorBrightness,
  colorLuminance,
  colorDistance,
  colorMixer,
  colorInverter,
  // Communication tools
  emailHeaderParser,
  emailTemplateBuilder,
  emailToMarkdown,
  emailAddressParser,
  emailSignatureGenerator,
  spfRecordGenerator,
  dkimValidator,
  telegramFormatter,
  teamsFormatter,
  ircFormatter,
  // Crypto tools
  md5Hash,
  sha1Hash,
  sha256Hash,
  sha384Hash,
  sha512Hash,
  sha3Hash,
  blake2Hash,
  ripemd160Hash,
  crc32Checksum,
  adler32Checksum,
  xxhash,
  murmurhash,
  hashIdentifier,
  multiHash,
  hmacSha256,
  hmacSha512,
  pbkdf2,
  bcryptGenerator,
  bcryptVerifier,
  aesEncrypt,
  aesDecrypt,
  rsaEncrypt,
  rsaDecrypt,
  chacha20Encrypt,
  chacha20Decrypt,
  rsaKeyGenerator,
  ecKeyGenerator,
  ed25519KeyGenerator,
  pemParser,
  jwkConverter,
  csrDecoder,
  certificateDecoder,
  keyFingerprint,
  passwordGenerator,
  passphraseGenerator,
  passwordStrength,
  pinGenerator,
  memorablePassword,
  passwordHashCheck,
  passwordEntropy,
  apiKeyGenerator,
  stringHash,
  // CSS tools
  cssFormatter,
  cssMinify,
  cssValidator,
  scssToCss,
  lessToCss,
  cssToScss,
  cssSpecificity,
  cssGradientGenerator,
  cssBoxShadow,
  cssBorderRadius,
  cssFlexboxGenerator,
  cssGridGenerator,
  // DateTime tools
  unixTimestamp,
  iso8601Converter,
  rfc2822Converter,
  epochConverter,
  dateFormatter,
  dateParser,
  julianDayConverter,
  excelDateConverter,
  relativeTime,
  dateToWords,
  timezoneConverter,
  utcConverter,
  dateDifference,
  dateAddSubtract,
  ageCalculator,
  workdaysCalculator,
  weekNumber,
  quarterCalculator,
  dayOfYear,
  leapYearChecker,
  daysInMonth,
  dateRangeGenerator,
  timezoneList,
  worldClock,
  durationCalculator,
  durationFormatter,
  timeParser,
  time12h24hConverter,
  countdownCalculator,
  meetingPlanner,
  cronBuilder,
  cronParser,
  cronNextRuns,
  cronValidator,
  cronToEnglish,
  englishToCron,
  rateLimiterCalculator,
  intervalCalculator,
  calendarGenerator,
  holidayLookup,
  icalGenerator,
  icalParser,
  vcardGenerator,
  vcardParser,
  // Diagram tools
  mermaidRenderer,
  mermaidEditor,
  plantumlAnalyzer,
  graphvizAnalyzer,
  sequenceDiagramEditor,
  flowchartEditor,
  erDiagramEditor,
  ganttChartEditor,
  mindMapEditor,
  asciiDiagram,
  qrCodeGenerator,
  qrWithLogo,
  styledQrCode,
  wifiQrCode,
  vcardQrCode,
  urlQrCode,
  bulkQrGenerator,
  code128Generator,
  code39Generator,
  ean13Generator,
  ean8Generator,
  upcAGenerator,
  upcEGenerator,
  itfGenerator,
  pdf417Info,
  dataMatrixInfo,
  lineChartGenerator,
  barChartGenerator,
  pieChartGenerator,
  scatterPlotGenerator,
  areaChartGenerator,
  radarChartGenerator,
  sparklineGenerator,
  jsonToChart,
  // Feeds tools
  rssParser,
  atomParser,
  rssGenerator,
  atomGenerator,
  rssValidator,
  feedMerger,
  jsonFeedParser,
  opmlParser,
  feedsSchemaOrgGenerator,
  schemaOrgValidator,
  jsonLdEditor,
  microdataExtractor,
  richSnippetPreview,
  breadcrumbGenerator,
  faqSchemaGenerator,
  productSchemaGenerator,
  // HTML tools
  htmlFormatter,
  htmlMinify,
  htmlValidator,
  htmlToText,
  htmlEntityEncoder,
  htmlEntityDecoder,
  htmlAttributeRemover,
  htmlPlayground,
  htmlTableGenerator,
  htmlListGenerator,
  faviconGenerator,
  // Image tools
  pngToJpg,
  jpgToPng,
  imageToWebp,
  webpToPng,
  imageToBase64,
  base64ToImage,
  imageToDataUrl,
  imageResizer,
  imageCropper,
  imageRotator,
  imageFlipper,
  imageCompressor,
  aspectRatioCalculator,
  imageBorderAdder,
  imageWatermark,
  roundCorners,
  circleCrop,
  thumbnailGenerator,
  imageSplitter,
  grayscale,
  sepia,
  invertColors,
  brightnessAdjuster,
  contrastAdjuster,
  blurFilter,
  sharpenFilter,
  pixelate,
  posterize,
  duotone,
  imageInfo,
  exifReader,
  exifRemover,
  colorPickerFromImage,
  dominantColors,
  imageHistogram,
  imageDiff,
  placeholderImage,
  // JWT tools
  jwtDecoder,
  jwtEncoder,
  jwtDebugger,
  jwtExpiryChecker,
  jwtClaimsBuilder,
  jwtRs256Generator,
  pasetoDecoder,
  oauthTokenDecoder,
  samlDecoder,
  fernetEncoder,
  // Identifiers tools
  uuidV1Generator,
  uuidV4Generator,
  uuidV5Generator,
  uuidV7Generator,
  ulidGenerator,
  nanoidGenerator,
  cuidGenerator,
  cuid2Generator,
  snowflakeIdGenerator,
  ksuidGenerator,
  objectidGenerator,
  shortIdGenerator,
  bulkIdGenerator,
  sessionTokenGenerator,
  // Git tools
  gitBranchNamer,
  gitCommandBuilder,
  gitCommitMessage,
  gitDiffViewer,
  gitignoreBuilder,
  gitIgnoreChecker,
  conventionalCommits,
  changelogParser,
  // DevOps tools
  dockerfileGenerator,
  dockerfileLinter,
  composeGenerator,
  composeValidator,
  k8sYamlGenerator,
  k8sYamlValidator,
  helmValuesGenerator,
  containerImageParser,
  // Legal tools
  privacyPolicyGenerator,
  cookiePolicyGenerator,
  termsOfServiceGenerator,
  copyrightNoticeGenerator,
  disclaimerGenerator,
  gdprStatementGenerator,
  // Reference tools
  countryCodeReference,
  currencyCodeReference,
  languageCodeReference,
  keyboardShortcutsReference,
  emojiReference,
  // Math tools
  lengthConverter,
  weightConverter,
  temperatureConverter,
  volumeConverter,
  areaConverter,
  speedConverter,
  timeUnitConverter,
  dataSizeConverter,
  pressureConverter,
  energyConverter,
  powerConverter,
  frequencyConverter,
  angleConverter,
  forceConverter,
  fuelEconomyConverter,
  currencyConverter,
  numberFormatter,
  percentageCalculator,
  ratioCalculator,
  fractionCalculator,
  percentageChange,
  tipCalculator,
  discountCalculator,
  markupCalculator,
  vatCalculator,
  compoundInterest,
  loanCalculator,
  bmiCalculator,
  expressionEvaluator,
  scientificCalculator,
  matrixCalculator,
  primeChecker,
  primeFactorization,
  gcdLcmCalculator,
  factorialCalculator,
  fibonacciGenerator,
  randomNumberGenerator,
  statisticsCalculator,
  standardDeviation,
  permutationCombination,
  quadraticSolver,
  bitwiseCalculator,
  romanNumeralConverter,
  scientificNotation,
  // Misc tools
  stringLength,
  stringObfuscator,
  characterRepeater,
  pigLatin,
  leetSpeak,
  emojiConverter,
  zalgoText,
  upsideDownText,
  fancyText,
  mimeTypeReference,
  htmlEntityReference,
  // Network tools
  networkHttpStatusReference,
  subnetCalculator,
  cidrCalculator,
  ipRangeCalculator,
  macAddressLookup,
  networkCurlBuilder,
  cidrToRange,
  integerToIp,
  ipInCidrChecker,
  ipInfoParser,
  ipToInteger,
  ipv6Compressor,
  ipv6Expander,
  rangeToCidr,
  harAnalyzer,
  httpHeadersReference,
  httpHeaderParser,
  mimeTypeLookup,
  // Regex tools
  regexTester,
  regexExplainer,
  regexReplace,
  regexSplit,
  regexExtract,
  regexGroups,
  regexFlagsTester,
  regexEscape,
  globToRegex,
  regexToGlob,
  regexOptimizer,
  commonPatterns,
  emailRegex,
  urlRegex,
  phoneRegex,
  ipRegex,
  dateRegex,
  creditCardRegex,
  passwordRegex,
  // SQL tools
  sqlFormatter,
  sqlMinify,
  sqlValidator,
  sqlToJsonLegacy,
  sqlParser,
  sqlExplainer,
  sqlToNosql,
  sqlDialectConverter,
  sqlQueryBuilder,
  sqlIndexSuggester,
  jsonToSqlInsert,
  csvToSqlInsert,
  connectionStringBuilder,
  dsnParser,
  redisCommandBuilder,
  mongodbQueryBuilder,
  elasticsearchQueryBuilder,
  databaseUrlConverter,
  erDiagramGenerator,
  sqlCreateTableGenerator,
  sqlDiff,
  sqlEscape,
  sqlExplainVisualizer,
  sqlIndexAdvisor,
  sqlInsertGenerator,
  sqlMigrationGenerator,
  sqlSchemaDiff,
  sqlSelectBuilder,
  // SVG tools
  svgOptimizer,
  svgViewer,
  svgToPngConverter,
  svgToJpg,
  svgToBase64,
  svgToDataUri,
  svgFormatter,
  svgPathEditor,
  svgToCss,
  svgSpriteGenerator,
  svgColorChanger,
  svgWaveGenerator,
  svgBlobGenerator,
  svgPatternGenerator,
  svgAvatarGenerator,
  svgDividerGenerator,
  svgBackgroundGenerator,
  // Validation tools
  emailValidator,
  urlValidator,
  phoneValidator,
  validationUuidValidator,
  macAddressValidator,
  ipv4Validator,
  ipv6Validator,
  domainValidator,
  hostnameValidator,
  slugValidator,
  semverValidator,
  hexColorValidator,
  creditCardValidator,
  isbnValidator,
  issnValidator,
  doiValidator,
  validationJsonValidator,
  validationXmlValidator,
  validationYamlValidator,
  validationTomlValidator,
  validationCsvValidator,
  validationHtmlValidator,
  validationCssValidator,
  javascriptValidator,
  validationSqlValidator,
  cronValidatorTool,
  // Web tools
  metaTagGenerator,
  ogGenerator,
  twitterCardGenerator,
  webSchemaOrgGenerator,
  robotsTxtGenerator,
  robotsTxtValidator,
  sitemapGenerator,
  sitemapValidator,
  canonicalUrlBuilder,
  hreflangGenerator,
  metaPreview,
  socialPreview,
  cspBuilder,
  cspValidator,
  corsBuilder,
  sriHashGenerator,
  securityHeadersCheck,
  hstsBuilder,
  permissionsPolicyBuilder,
  xssFilterTester,
] as const;

/**
 * Register all tools with the global registry.
 * This function is idempotent - calling it multiple times is safe.
 */
export function registerAllTools(): void {
  for (const tool of ALL_TOOLS) {
    if (!globalRegistry.has(tool.meta.id)) {
      globalRegistry.registerTool(tool);
    }
  }
}

/**
 * Get the count of available tools.
 */
export function getToolCount(): number {
  return ALL_TOOLS.length;
}

// Auto-register on import
registerAllTools();
