/**
 * Error codes for tool execution failures.
 * Organized by category prefix.
 */

// Input validation errors
export const INPUT_REQUIRED = "INPUT_REQUIRED";
export const INPUT_INVALID_TYPE = "INPUT_INVALID_TYPE";
export const INPUT_TOO_LARGE = "INPUT_TOO_LARGE";
export const INPUT_INVALID_FORMAT = "INPUT_INVALID_FORMAT";
export const INPUT_EMPTY = "INPUT_EMPTY";

// Parsing errors
/** @deprecated Use JSON_PARSE_ERROR instead */
export const PARSE_INVALID_JSON = "JSON_PARSE_ERROR";
export const PARSE_INVALID_YAML = "PARSE_INVALID_YAML";
export const PARSE_INVALID_XML = "PARSE_INVALID_XML";
export const PARSE_INVALID_CSV = "PARSE_INVALID_CSV";
export const PARSE_INVALID_TOML = "PARSE_INVALID_TOML";
export const PARSE_INVALID_INI = "PARSE_INVALID_INI";
export const PARSE_INVALID_MARKDOWN = "PARSE_INVALID_MARKDOWN";
export const PARSE_SYNTAX_ERROR = "PARSE_SYNTAX_ERROR";

// JSON-specific errors
export const JSON_PARSE_ERROR = "JSON_PARSE_ERROR";
export const JSON_INVALID_PATH = "JSON_INVALID_PATH";
export const JSON_PATH_NOT_FOUND = "JSON_PATH_NOT_FOUND";
export const JSON_CIRCULAR_REFERENCE = "JSON_CIRCULAR_REFERENCE";

// YAML-specific errors
export const YAML_PARSE_ERROR = "YAML_PARSE_ERROR";
export const YAML_INVALID_SYNTAX = "YAML_INVALID_SYNTAX";
export const YAML_DUPLICATE_KEY = "YAML_DUPLICATE_KEY";

// XML-specific errors
export const XML_PARSE_ERROR = "XML_PARSE_ERROR";
export const XML_INVALID_SYNTAX = "XML_INVALID_SYNTAX";
export const XML_XPATH_ERROR = "XML_XPATH_ERROR";
export const XML_XPATH_NO_MATCH = "XML_XPATH_NO_MATCH";

// CSV-specific errors
export const CSV_PARSE_ERROR = "CSV_PARSE_ERROR";
export const CSV_INVALID_DELIMITER = "CSV_INVALID_DELIMITER";
export const CSV_COLUMN_MISMATCH = "CSV_COLUMN_MISMATCH";
export const CSV_EMPTY_DATA = "CSV_EMPTY_DATA";

// TOML-specific errors
export const TOML_PARSE_ERROR = "TOML_PARSE_ERROR";
export const TOML_INVALID_SYNTAX = "TOML_INVALID_SYNTAX";

// INI-specific errors
export const INI_PARSE_ERROR = "INI_PARSE_ERROR";
export const INI_INVALID_SYNTAX = "INI_INVALID_SYNTAX";

// Data format errors
export const JSONC_PARSE_ERROR = "JSONC_PARSE_ERROR";
export const MESSAGEPACK_DECODE_ERROR = "MESSAGEPACK_DECODE_ERROR";
export const PROTOBUF_DECODE_ERROR = "PROTOBUF_DECODE_ERROR";
export const AVRO_DECODE_ERROR = "AVRO_DECODE_ERROR";
export const BASE64_DECODE_ERROR = "BASE64_DECODE_ERROR";
export const NDJSON_PARSE_ERROR = "NDJSON_PARSE_ERROR";
export const NDJSON_INVALID_LINE = "NDJSON_INVALID_LINE";
export const HJSON_PARSE_ERROR = "HJSON_PARSE_ERROR";
export const JSON5_PARSE_ERROR = "JSON5_PARSE_ERROR";

// Text-specific errors
export const TEXT_REGEX_INVALID = "TEXT_REGEX_INVALID";
export const TEXT_PATTERN_NO_MATCH = "TEXT_PATTERN_NO_MATCH";
export const TEXT_ENCODING_ERROR = "TEXT_ENCODING_ERROR";
export const TEXT_EMPTY_INPUT = "TEXT_EMPTY_INPUT";

// Markdown-specific errors
export const MARKDOWN_PARSE_ERROR = "MARKDOWN_PARSE_ERROR";
export const MARKDOWN_INVALID_FRONTMATTER = "MARKDOWN_INVALID_FRONTMATTER";
export const MARKDOWN_NO_HEADINGS = "MARKDOWN_NO_HEADINGS";

// Diff-specific errors
export const DIFF_TOO_LARGE = "DIFF_TOO_LARGE";
export const DIFF_IDENTICAL = "DIFF_IDENTICAL";

// Execution errors
export const EXEC_FAILED = "EXEC_FAILED";
export const EXEC_TIMEOUT = "EXEC_TIMEOUT";
export const EXEC_TOOL_NOT_FOUND = "EXEC_TOOL_NOT_FOUND";

// Limit errors
export const LIMIT_SIZE = "LIMIT_SIZE";
export const LIMIT_RATE = "LIMIT_RATE";
export const LIMIT_DAILY_OPS = "LIMIT_DAILY_OPS";

/**
 * All error codes grouped by category.
 */
export const ERROR_CODES = {
  INPUT: {
    REQUIRED: INPUT_REQUIRED,
    INVALID_TYPE: INPUT_INVALID_TYPE,
    TOO_LARGE: INPUT_TOO_LARGE,
    INVALID_FORMAT: INPUT_INVALID_FORMAT,
    EMPTY: INPUT_EMPTY,
  },
  PARSE: {
    INVALID_JSON: PARSE_INVALID_JSON,
    INVALID_YAML: PARSE_INVALID_YAML,
    INVALID_XML: PARSE_INVALID_XML,
    INVALID_CSV: PARSE_INVALID_CSV,
    INVALID_TOML: PARSE_INVALID_TOML,
    INVALID_INI: PARSE_INVALID_INI,
    INVALID_MARKDOWN: PARSE_INVALID_MARKDOWN,
    SYNTAX_ERROR: PARSE_SYNTAX_ERROR,
  },
  JSON: {
    PARSE_ERROR: JSON_PARSE_ERROR,
    INVALID_PATH: JSON_INVALID_PATH,
    PATH_NOT_FOUND: JSON_PATH_NOT_FOUND,
    CIRCULAR_REFERENCE: JSON_CIRCULAR_REFERENCE,
  },
  YAML: {
    PARSE_ERROR: YAML_PARSE_ERROR,
    INVALID_SYNTAX: YAML_INVALID_SYNTAX,
    DUPLICATE_KEY: YAML_DUPLICATE_KEY,
  },
  XML: {
    PARSE_ERROR: XML_PARSE_ERROR,
    INVALID_SYNTAX: XML_INVALID_SYNTAX,
    XPATH_ERROR: XML_XPATH_ERROR,
    XPATH_NO_MATCH: XML_XPATH_NO_MATCH,
  },
  CSV: {
    PARSE_ERROR: CSV_PARSE_ERROR,
    INVALID_DELIMITER: CSV_INVALID_DELIMITER,
    COLUMN_MISMATCH: CSV_COLUMN_MISMATCH,
    EMPTY_DATA: CSV_EMPTY_DATA,
  },
  TOML: {
    PARSE_ERROR: TOML_PARSE_ERROR,
    INVALID_SYNTAX: TOML_INVALID_SYNTAX,
  },
  INI: {
    PARSE_ERROR: INI_PARSE_ERROR,
    INVALID_SYNTAX: INI_INVALID_SYNTAX,
  },
  DATA: {
    JSONC_PARSE_ERROR: JSONC_PARSE_ERROR,
    MESSAGEPACK_DECODE_ERROR: MESSAGEPACK_DECODE_ERROR,
    PROTOBUF_DECODE_ERROR: PROTOBUF_DECODE_ERROR,
    AVRO_DECODE_ERROR: AVRO_DECODE_ERROR,
    BASE64_DECODE_ERROR: BASE64_DECODE_ERROR,
    NDJSON_PARSE_ERROR: NDJSON_PARSE_ERROR,
    NDJSON_INVALID_LINE: NDJSON_INVALID_LINE,
    HJSON_PARSE_ERROR: HJSON_PARSE_ERROR,
    JSON5_PARSE_ERROR: JSON5_PARSE_ERROR,
  },
  TEXT: {
    REGEX_INVALID: TEXT_REGEX_INVALID,
    PATTERN_NO_MATCH: TEXT_PATTERN_NO_MATCH,
    ENCODING_ERROR: TEXT_ENCODING_ERROR,
    EMPTY_INPUT: TEXT_EMPTY_INPUT,
  },
  MARKDOWN: {
    PARSE_ERROR: MARKDOWN_PARSE_ERROR,
    INVALID_FRONTMATTER: MARKDOWN_INVALID_FRONTMATTER,
    NO_HEADINGS: MARKDOWN_NO_HEADINGS,
  },
  DIFF: {
    TOO_LARGE: DIFF_TOO_LARGE,
    IDENTICAL: DIFF_IDENTICAL,
  },
  EXEC: {
    FAILED: EXEC_FAILED,
    TIMEOUT: EXEC_TIMEOUT,
    TOOL_NOT_FOUND: EXEC_TOOL_NOT_FOUND,
  },
  LIMIT: {
    SIZE: LIMIT_SIZE,
    RATE: LIMIT_RATE,
    DAILY_OPS: LIMIT_DAILY_OPS,
  },
} as const;
